trial_name: _bench_run
observables:
- GSMF
- CGD
param_mode: custom
free_params:
- omega_m
- sigma_8
fixed_params:
  kappa_w: 3.2909
  e_w: 0.4769
  M_seed: 1.1914
  v_kin: 1.1395
  eps_kin: 0.2325
gaussian_priors:
  omega_m:
    mu: 0.14176
    sigma: 0.0011
  sigma_8:
    mu: 0.8102
    sigma: 0.006
mcmc:
  nburn: 20
  nrun: 180
  parallel: true
