# Trial: Cluster-only statistics (CGD + CGED), subgrid parameters only
trial_name: CGD_CGED_cluster

observables:
  - CGD
  - CGED

param_mode: subgrid
fixed_params: {}
bias_params: []
flat_prior_indices: []

mcmc:
  nwalkers: 100
  nburn: 200
  nrun: 4000
  parallel: true

data:
  DirIn: ../data/400MPC_RUNS_5SG_2COSMO_PARAM/HAvoCC/
  design_file: ../data/FinalDesign.txt
  num_sims: 39
  start_sim_idx: 1
  exp_variance: 0.95
  z_index: 0
  model_dir: ../models/

obs_dirs:
  cgd: /home/nramachandra/Projects/Hydro_runs/HAvoCC/havocc/analysis/modules/halo_profile_modules/ClusterGasDensityProfile/data/
  cged: /home/nramachandra/Projects/Hydro_runs/HAvoCC/havocc/analysis/modules/halo_profile_modules/ClusterGasElectronDensityProfile/data/

output_dir: results/
